### PR TITLE
Fix for floating point rounding error

### PR DESCRIPTION
**Pull request by yamiM0NSTER**
Fixes final pool fee down to 0.001%

Test before merging.

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
@yamiM0NSTER any pools running this patch?

**Comment by yamiM0NSTER** [comment]
it's block explorer sided to correctly represent pool fees.

**Comment by RocksteadyTC** [comment]
@yamiM0NSTER any explorers running this patch, I meant to say?

**Comment by yamiM0NSTER** [comment]
ah, you would have to ask service operators, as nobody really said anything about it.

**Pull request merged**
