### PR TITLE
Block-Explorer - Devopsralf

### PR DESCRIPTION
**Pull request by devopsralf**
Ok here is my submission for the bounty. Tested and works wonderfully. 

A few things to note:

Some json is not returned by trutlecoind, like timestamps on mempool, so those feature using the data from that are commented out and can easily be enabled once turtlecoind is updated. 

Really hope this helps!

Devopsralf - TRTLv2RCPuD7AaaVpQkRPF59MMLx5WW3qFxwJz4Doy7dHhNA6UuQjEpLL3rpUQS4RXdQn8fb4P1XC3K62GeJjGgG8DP9LNaTrNL

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
Ralf, Thanks. Is there a URL where this is currently running successfully using this config?

**Comment by devopsralf** [comment]
It is running local but I can prop one up quickly. It wouldn't be a permanent thing.

**Comment by devopsralf** [comment]
Im just using the php internal web server to test.

**Comment by devopsralf** [comment]
Working demo here: turtleblocks.dreamitsystems.com
resolves to 52.191.198.51

**Comment by RocksteadyTC** [comment]
Minor cosmetic defects: tooltips mentions tail emission, karbo is still mentioned in tool tips. Please post your TRTL address as a reply. Thank you for your contribution, Ralf.

**Pull request merged**
